source_files = Rake::FileList.new("**/*.md", "**/*.markdown") do |fl|
  fl.exclude("~*")
  fl.exclude(/^scratch\//)
  fl.exclude("temp.md")
end

task :default => :html
task :html => source_files.ext(".html")

rule ".html" => ".md" do |t|
  sh "pandoc -o #{t.name} #{t.source}"
end

rule ".html" => ".markdown" do |t|
  sh "pandoc -o #{t.name} #{t.source}"
end

# Does the same as the rule
# %W[ch1.md ch2.md ch3.md].each do |md_file|
#   html_file = File.basename(md_file, ".md") + ".html"
#   file html_file => md_file do
#     sh "pandoc -o #{html_file} #{md_file}"
#   end
# end
